###########################################################
                BaseGeometry  tests
###########################################################

"""
>>> import sys
>>> sys.path.append("..")
>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry
>>> b1 = BaseGeometry()
>>> b1.area()
Traceback (most recent call last):
  ...
Exception: area() is not implemented
>>> b1.integer_validator("one", 1)
>>> b1.integer_validator("tow", "one")
Traceback (most recent call last):
  ...
TypeError: tow must be an integer
>>> b1.integer_validator("five", "ahmad")
Traceback (most recent call last):
  ...
TypeError: five must be an integer
>>> b1.integer_validator("six", 23.2)
Traceback (most recent call last):
  ...
TypeError: six must be an integer
>>> b1.integer_validator("seven", {"ahmad":1})
Traceback (most recent call last):
  ...
TypeError: seven must be an integer
>>> b1.integer_validator("tow", [1, 2])
Traceback (most recent call last):
  ...
TypeError: tow must be an integer
>>> b1.integer_validator("tow", {1, 3})
Traceback (most recent call last):
  ...
TypeError: tow must be an integer
>>> b1.integer_validator("tow", (1,))
Traceback (most recent call last):
  ...
TypeError: tow must be an integer
>>> b1.integer_validator("tow", 5j + 1)
Traceback (most recent call last):
  ...
TypeError: tow must be an integer
>>> b1.integer_validator("tow", True)
Traceback (most recent call last):
  ...
TypeError: tow must be an integer
>>> b1.integer_validator("tow", 0)
Traceback (most recent call last):
  ...
ValueError: tow must be greater than 0
>>> b1.integer_validator("tow", None)
Traceback (most recent call last):
  ...
TypeError: tow must be an integer
>>> b1.integer_validator()
Traceback (most recent call last):
  ...
TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'
>>> b1.integer_validator("ahmad", 3, 4)
Traceback (most recent call last):
  ...
TypeError: integer_validator() takes 3 positional arguments but 4 were given
>>> b1.integer_validator("three", -3)
Traceback (most recent call last):
  ...
ValueError: three must be greater than 0
>>> b1.integer_validator("four", 0)
Traceback (most recent call last):
  ...
ValueError: four must be greater than 0

"""
